name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install jq
      run: sudo apt-get install jq
    - name: execute update metadata
      run: ./update-metadata.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: vermapraveen
    - name: Run a one-line script2
      run: ls ../    
    - name: Run a one-line script3
      run: ls ../../
      
